### ISSUE TITLE
How to read the value of a Local (L:) SimVar?

### ISSUE THREAD

**Issue by markidoet** [theomessin/jetbridge#9]
Excuse me,
Example project works normally when setting L:Var values, but how do I get current value L:Var ? 

Thanks.

**Comment by scott-vincent** [comment]
For a write you send, e.g. "1 (>L:A32NX_OVHD_PNEU_APU_BLEED_PB_IS_ON, bool)"
For a read, you would just send "(L:A32NX_OVHD_PNEU_APU_BLEED_PB_IS_ON, bool)"

**Comment by theomessin** [comment]
If you're just using `execute_calculator_code` outside jetbridge, Scott's answer would work. The current develop branch does not support reading LVars just yet. You can use the #2 branch to read a double LVar value by using Scott's answer, although the plan is for this to change and this PR will probably close. I'm really busy and not working on this at the moment, I'm planning on resuming work on jetbridge in June.

```cpp
auto result = new double;
client->ExecuteCalculatorCode("(L:A32NX_RMP_L_VHF2_STANDBY_FREQUENCY)", result);
std::cout << result << std::endl;
delete result;  // don't forget to do this!
```

**Comment by theomessin** [comment]
I'll keep this issue open until we have a documented solution to read simulation variables merged in the `develop` branch.

**Comment by markidoet** [comment]
Thanks for your reply :)
I tried to use this:

> auto result = new double;
client->ExecuteCalculatorCode("(L:A32NX_RMP_L_VHF2_STANDBY_FREQUENCY)", result);
std::cout << result << std::endl;
delete result;  // don't forget to do this!

And get error

> Exception thrown at 0x00007FFAA3FF13FD (vcruntime140d.dll) in Example.exe: 0xC0000005: Access violation reading location 0x0000000000000004.

![Screenshot 2021-05-03 020127](https://user-images.githubusercontent.com/77946544/116824381-0a49be00-abb4-11eb-8899-b88df77c7814.png)

Thanks,

**Comment by theomessin** [comment]
I think this is because the requests are timing out (i.e. the jetbridge wasm module isn't replying) and we're trying to `delete 0`.
You can see that the `Client->Request` method has a timeout (default is 1000 milliseconds)
https://github.com/theomessin/jetbridge/blob/b67f897a83728f14cdc587a2860dbe1d78bafb93/Client/Client.cc#L46-L50

Eventually we should add checks to prevent the Client code from crashing. Something like this should fix this:
```cpp
  auto response = this->Request(data);
  std::memcpy(result, response->data, sizeof(double));
  if (response != nullptr) delete response;
```

**Comment by markidoet** [comment]
Thanks, i modify this line too in main function Example:

> std::string code;
   std::cin >> code;

to 

> std::string code;
   std::getline(std::cin, code);

And now, get and set Local Var is working. 
Thanks Thanks Thanks

**Comment by theomessin** [comment]
Hey @markidoet, please see [release 0.2.0](https://github.com/theomessin/jetbridge/releases/tag/v0.2.0)
https://github.com/theomessin/jetbridge/blob/2134ad182d63e8b55d50421296e1633d7edd78f1/Example/Example.cc#L54-L55
